FROM archlinux
RUN patched_glibc=glibc-linux4-2.33-4-x86_64.pkg.tar.zst \
    && curl -LO "https://raw.githubusercontent.com/sickcodes/Docker-OSX/master/${patched_glibc}" \
    && bsdtar -C / -xvf "${patched_glibc}" || echo "Everything is fine."

RUN packman --noconfirm  install python3 
ADD sample.py /home/sample.py
CMD ["/home/sample.py"]
ENTRYPOINT ["python3"]


